# Generated by Django 5.2.6 on 2025-09-22 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('age_group', models.PositiveIntegerField(verbose_name='Средний возраст учеников')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема урока')),
                ('hours', models.PositiveIntegerField(default=1, verbose_name='Кол-во часов/уроков')),
                ('preferences', models.TextField(blank=True, null=True, verbose_name='Пожелания')),
                ('generated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lesson_plans/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='lesson_plans/docx/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to=settings.AUTH_USER_MODEL)),
                ('study_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='lesson_plans.studyclass')),
            ],
        ),
    ]
