# Generated by Django 5.2.6 on 2025-09-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('lesson_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='study_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='classes.studyclass'),
        ),
        migrations.DeleteModel(
            name='StudyClass',
        ),
    ]
