# Generated by Django 5.2.6 on 2025-09-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_plans', '0002_alter_lessonplan_study_class_delete_studyclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'План урока', 'verbose_name_plural': 'Планы уроков'},
        ),
    ]
